### ISSUE TITLE
Plotting with Labels

### ISSUE THREAD

**Issue by hcars** [NSSAC/graph-plot#11]
Currently, there is no way to plot nodes with labels. _igraph_ has a special format called `ncol`. `ncol` treats a file as an edge list but handles non-integer node IDs unlike `edges`. The node IDs are saved as a field called _name_. The easiest solution to supporting some form of node labels seems to be have a flag that works with files interpretable as an `ncol` to get node labels and plot those labels.

Thoughts? @cckuhlman @Lucaslhm @ssravi-1984

**Comment by cckuhlman** [comment]
I think this is a good way to go.

Note, Henry, that we might look at other graph plotting codes.  Graphia is one.  I sent that email with that MS Word file about tools, and graphia seemed to be an up-and-comer in the graph visualization world.  So Graphia (or other may do this more readily.

My guess, for what it is worth, is that we will have multiple plotting codes:  different choice of plot codes for different goals.

Do not misunderstand me.  What you are doing is great:  finding these issues, looking into them, fantastic.  But let us talk through before implementing because we have to balance things.  For example, plotting labels on nodes ... I guess it is good and useful for smaller graphs (original or communities), but I am guessing that a graph will not have to have very many nodes for labels on nodes, in a graph plot, to swamp the entire plot.  But I could be wrong.

So let us bring this up and talk in your meeting, with Ravi and Lucas, in the next meeting, after the tutorial.

**Comment by hcars** [comment]
> Do not misunderstand me. What you are doing is great: finding these issues, looking into them, fantastic. But let us talk through before implementing because we have to balance things. For example, plotting labels on nodes ... I guess it is good and useful for smaller graphs (original or communities), but I am guessing that a graph will not have to have very many nodes for labels on nodes, in a graph plot, to swamp the entire plot. But I could be wrong.
> 
> So let us bring this up and talk in your meeting, with Ravi and Lucas, in the next meeting, after the tutorial.


@cckuhlman @ssravi-1984 @dmachi 

Do we have a list of features that we are interested in supporting for the graph plotting suite? If we don't have a document detailing a list of desired features, I think we should create one. Once we have enumerated features that we want, we can choose the most important features and decide how to implement them. I think this will allow us to make more systematic designs about choosing the ideal software to support different features.

**Comment by hcars** [comment]
I added a way to handle this that is also on the induced subgraph pull request. Note that for more than node attribute, users should be using graphml or another structued markup graph language for igraph to load the attributes.
